### ISSUE TITLE
NPE when closing napari-imagej

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#182]
While ensuring that #141 has been fixed, I found that running that same procedure produces 
* Boot napari-imagej
* Open the ImageJ legacy UI
* Transfer some data from napari to ImageJ
* Auto Threshold that data (Ctrl + Shift + T, Apply, close the window)
* Create Mask from the threshold (search "Create Mask" in the searchbar, run it)
* Transfer the mask back to napari
* Click the close button on napari

This yields the following NPE:

```
java.lang.NullPointerException
	at net.imagej.legacy.translate.ColorTableHarmonizer.setImagePlusLUTToFirstInView(ColorTableHarmonizer.java:199)
	at net.imagej.legacy.translate.ColorTableHarmonizer.updateLegacyImage(ColorTableHarmonizer.java:118)
	at net.imagej.legacy.translate.Harmonizer.updateLegacyImage(Harmonizer.java:102)
	at net.imagej.legacy.LegacyImageMap.onEvent(LegacyImageMap.java:686)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:298)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:272)
	at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:971)
	at org.scijava.event.DefaultEventBus.access$101(DefaultEventBus.java:54)
	at org.scijava.event.DefaultEventBus$1.run(DefaultEventBus.java:188)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:111)
	at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:182)
	at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:73)
	at org.scijava.event.DefaultEventService.publish(DefaultEventService.java:102)
	at org.scijava.display.AbstractDisplay.update(AbstractDisplay.java:121)
	at net.imagej.display.DefaultImageDisplay.update(DefaultImageDisplay.java:311)
	at net.imagej.display.DefaultOverlayService.removeOverlay(DefaultOverlayService.java:151)
	at net.imagej.threshold.DefaultThresholdService.removeThreshold(DefaultThresholdService.java:125)
	at net.imagej.threshold.DefaultThresholdService.onEvent(DefaultThresholdService.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:298)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:272)
	at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:971)
	at org.scijava.event.DefaultEventBus.access$101(DefaultEventBus.java:54)
	at org.scijava.event.DefaultEventBus$1.run(DefaultEventBus.java:188)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:111)
	at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:182)
	at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:73)
	at org.scijava.event.DefaultEventService.publish(DefaultEventService.java:102)
	at org.scijava.display.AbstractDisplay.close(AbstractDisplay.java:135)
	at net.imagej.legacy.DefaultLegacyHooks.unregisterImage(DefaultLegacyHooks.java:201)
	at ij.ImagePlus.close(ImagePlus.java:475)
	at net.imagej.legacy.IJ1Helper$5.run(IJ1Helper.java:1412)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
```
This doesn't affect behavior, though, so it's not top priority.

**Comment by gselzer** [comment]
I can't seem to replicate this anymore, maybe this got fixed by changes in Fiji 2.10/2.11?

@hinerm @elevans would either of you be willing to try and reproduce this? If you can't can you close this issue? We can always re-open if someone else experiences it...

**Comment by hinerm** [comment]
No NPE for me!

**Comment by hinerm** [comment]
uh oh.. although now it seems like the process isn't closing.. I am worried ImageJ isn't disposed 😿

**Comment by gselzer** [comment]
Really? That's not something I've seen before, @hinerm. Is it reproducible?

Sometimes it won't give me a new command line prompt until I try to type something, but I figured that wasn't something I did.

**Comment by gselzer** [comment]
Great!

(For those wondering, @hinerm was unable to reproduce)

We can re-open if anyone else can reproduce.

**Comment by hinerm** [comment]
@gselzer OK sorry... I *can* reproduce. Consistently when I go through the steps of the original issue I do not get an NPE but my process doesn't quit, can't ctrl+c out of it, etc...

if I just open an image and transfer it back and forth it's OK. It's only if I do the additional processing steps in ImageJ.

**Comment by hinerm** [comment]
Closing in favor of https://github.com/imagej/napari-imagej/issues/141
