### ISSUE TITLE
Computer ops do not prevent user from selecting out == in

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#233]
When running a computer op, napari-imagej does not issue an error message when specifying the same layer for both input and output. But most computer ops fail when attempting to use the same image for input and output. Example steps to reproduce:

1. Launch napari-imagej via *Plugins &rarr; ImageJ2 (napari-imagej)*
2. Open an image via *File &rarr; Open File(s)...* – I used `NESb_C2_TP1.tiff` from `NESb.zip` of the [SCIFIO sample images](https://scif.io/images)
3. Type `gauss` into the napari-imagej search bar
4. Expand the `Ops (13)` tree branch
5. Double click `filter.gauss(img "out", img "in", double[] "sigmas") -> (img "out")`
6. Click <kbd>OK</kbd> noting that the "out" and "in" point to the same layer
8. Observe traceback in the console

```python
[ERROR] Command errored: filter.gauss
java.lang.ArrayIndexOutOfBoundsException: 1
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.canUseArrayImgFactory(SeparableSymmetricConvolution.java:445)
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.getImgFactory(SeparableSymmetricConvolution.java:451)
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.convolveRealTypeFloat(SeparableSymmetricConvolution.java:142)
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.convolve(SeparableSymmetricConvolution.java:125)
	at net.imagej.ops.filter.gauss.DefaultGaussRAI.compute(DefaultGaussRAI.java:87)
	at net.imagej.ops.filter.gauss.DefaultGaussRAI.compute(DefaultGaussRAI.java:58)
	at net.imagej.ops.special.hybrid.UnaryHybridCF.run(UnaryHybridCF.java:75)
	at net.imagej.ops.special.hybrid.UnaryHybridCF.run(UnaryHybridCF.java:97)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:960)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:136)
	at net.imagej.ops.OpListingModule.run(OpListingModule.java:68)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[java.lang.Enum.toString] [ERROR] Command errored: filter.gauss
java.lang.ArrayIndexOutOfBoundsException: 1
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.canUseArrayImgFactory(SeparableSymmetricConvolution.java:445)
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.getImgFactory(SeparableSymmetricConvolution.java:451)
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.convolveRealTypeFloat(SeparableSymmetricConvolution.java:142)
	at net.imglib2.algorithm.gauss3.SeparableSymmetricConvolution.convolve(SeparableSymmetricConvolution.java:125)
	at net.imagej.ops.filter.gauss.DefaultGaussRAI.compute(DefaultGaussRAI.java:87)
	at net.imagej.ops.filter.gauss.DefaultGaussRAI.compute(DefaultGaussRAI.java:58)
	at net.imagej.ops.special.hybrid.UnaryHybridCF.run(UnaryHybridCF.java:75)
	at net.imagej.ops.special.hybrid.UnaryHybridCF.run(UnaryHybridCF.java:97)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:960)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:136)
	at net.imagej.ops.OpListingModule.run(OpListingModule.java:68)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
---------------------------------------------------------------------------
java.lang.ArrayIndexOutOfBoundsException  Traceback (most recent call last)
File ~/code/napari/napari-imagej/src/napari_imagej/widgets/napari_imagej.py:181, in NapariImageJWidget._update_progress(self=<napari_imagej.widgets.napari_imagej.NapariImageJWidget object>, event=<java object 'org.scijava.module.event.ModuleErroredEvent'>)
    179     pm.close(module)
    180 if isinstance(event, jc.ModuleErroredEvent):
--> 181     raise event.getException()
        event = <java object 'org.scijava.module.event.ModuleErroredEvent'>

java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 1
```

**Comment by gselzer** [comment]
It seems like that would be *pretty tricky* to implement in practice.

Right now, napari-imagej delegates completely to magicgui to make the layer selector boxes. As such, any solution would require overriding the layer `ComboBox`es.

I think that if we did this we'd need to add an I/O indicator field to each selector. Then, for each layer, we'd have to pass the `Layer` choices function to each `ComboBox` that is created by a module. More specifically, it should probably be a `Callable` object that knows whether it is an input or output `ComboBox`, along with a callback mechanism that *other* `ComboBoxes` can use to identify the `Layer`s that are off-limits.

While I bet it's possible, it certainly hurts my brain to think about. Do you envision an easier way to do this, @ctrueden?

**Comment by ctrueden** [comment]
Yeah, we can just do post-dismissal validation, similar to how we handle the settings dialog. If it's a computer op and the in == out, display an error dialog and do not proceed with the execution.

**Comment by gselzer** [comment]
> Yeah, we can just do post-dismissal validation, similar to how we handle the settings dialog. If it's a computer op and the in == out, display an error dialog and do not proceed with the execution.

You know @ctrueden, since this is a problem outside of napari-imagej, maybe this validation should be added to the `OpListingModule` upstream? Then it would be fixed everywhere...
